import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ['latin']})


export const metadata: Metadata = {
  title: "Next js wordpress graphql",
  description: "Generated by abhay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      <div className="max-w-195 p-4 md:p-10 mx-auto bg-background min-h-screen">
          <Header/>
         {children}
         <Footer/>
        </div>
      </body>
    </html>
  );
}
